---
"data_dir": /Users/ConradOakes/Massachusetts Institute of Technology/GallowayLab - 2021.01.17.NT_FT_2dpi_timelapse/3dpi_timelapse_short
"cp_loc": /Applications/CellProfiler.app
"fiji_loc": /Applications/Fiji.app
"pipe_loc": /Users/ConradOakes/CellBaum/
"final_dir": /Users/ConradOakes/Desktop/Galloway_2021
"log_loc": /Users/ConradOakes/CellBaum/snakemake_logs
"Name_keys":
 - 2021.01.18_10X_time_well_000{pp}_Z{ttt}_CH1.tif
 - 2021.01.18_10X_time_well_000{pp}_Z{ttt}_CH3_corrected.tiff
 - 2021.01.18_10X_time_well_000{pp}_Z{ttt}_CH4.tif
 - 2021.01.18_10X_time_well_000{pp}_Z{ttt}_Overlay.tif
"Prefix": 
 - "CH1"
 - "CH3"
 - "CH4"
 - "Overlay"